name: Prueba Cron

on:
  schedule:
    - cron: '*/5 * * * *'  # se ejecuta cada 5 minutos (hora UTC)
  workflow_dispatch:        # para dispararlo manualmente

jobs:
  debug:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # opcional, solo en main
    steps:
      - name: Mensaje de prueba
        run: |
          echo "Hola, cron funciona!"
          echo "Hora UTC: $(date -u)"
          echo "Hora local (Ubuntu): $(date)"
