name: Actualizar precios gel - Prueba Cron

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# ESTO ES VITAL PARA EL CRON
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11  # Estable y soportado

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install pandas requests beautifulsoup4 openpyxl

      - name: Ejecutar scraper
        run: python scraper.py

      - name: Commit y push de CSV actualizado
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add historial_precios.csv
          git commit -m "Actualizar historial de precios [GitHub Actions]" || echo "No hay cambios"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/franciscosalusso-ux/gel-costos.git main
