name: Actualizar precios gel

on:
  schedule:
    # 9 AM Argentina = UTC-3 => 12 UTC
    - cron: '0 12 * * *'
  workflow_dispatch: # permite ejecutar manualmente

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.14

      - name: Instalar dependencias
        run: |
          pip install pandas requests beautifulsoup4 openpyxl streamlit

      - name: Ejecutar scraper
        run: |
          python scraper.py

      - name: Commit y push de CSV actualizado
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "actions@github.com"
          git add historial_precios.csv
          git diff --cached --quiet || git commit -m "Actualizar historial de precios [GitHub Actions]"
          git push


      - name: Commit y push de CSV actualizado
        run: |
          git add historial_precios.csv
          git commit -m "Actualizar historial de precios [GitHub Actions]" || echo "No hay cambios que commitear"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
